# Generated by Django 5.2.4 on 2026-09-05 03:40

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=80)),
                ('user', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('record_id', models.IntegerField()),
                ('details', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
