# Generated by Django 5.2.4 on 2026-09-05 03:40

import django.core.validators
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KycRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_request_id', models.IntegerField(unique=True)),
                ('customer_name', models.CharField(max_length=160)),
                ('customer_email', models.EmailField(max_length=254)),
                ('risk_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('submission_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=16)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_by', models.EmailField(blank=True, max_length=254)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['submission_date', 'kyc_request_id'],
            },
        ),
    ]
